### ISSUE TITLE
`require-description` shouldn't require a description for `eslint-enable`

### ISSUE THREAD

**Issue by DetachHead** [eslint-community/eslint-plugin-eslint-comments#131]
when using `eslint-enable`, there's already an `eslint-disable` comment with the description on it so there's no reason to provide another description when re-enabling it.

```ts
describe('any', () => {
    /* eslint-disable @typescript-eslint/no-explicit-any -- testing the any type */
    test('pass', () => {
        exactly<any>()(any)
    })
    test('fail', () => {
        // @ts-expect-error doesn't match
        exactly<any>()(number)
        // @ts-expect-error doesn't match
        exactly<number>()(any)
    })
    /* eslint-enable @typescript-eslint/no-explicit-any -- testing the any type */
})
```

original issue: https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/61

**Comment by dimitropoulos** [comment]
this seems the same as: https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/49

which is to say: I 100% agree!

**Comment by tylerlaprade** [comment]
I have always used it like this, using this config:
`"eslint-comments/require-description": ["error", { "ignore": ["eslint-enable"] }],`
