### ISSUE TITLE
`no-unused-disable` doesn't work with flat config

### ISSUE THREAD

**Issue by teppeis** [eslint-community/eslint-plugin-eslint-comments#133]
This rule is implemented by [patching](https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/57dac8425e2761d215aa7b41e498c94fd0fdea83/lib/utils/patch.js) `Linter`, which seems to be causing this problem with new flat config.

The flat config allows `reportUnusedDisableDirectives` to be included in shareable config.
The new RFC will also allow for more configuration flexibility (in ESLint v9 ?).

- https://github.com/eslint/rfcs/pull/100

So it would be good to make this rule deprecated in the future.

original: https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/79

**Comment by ota-meshi** [comment]
Thank you for posting the issue.
As you say, I think `no-unused-disable` should be deprecated.
I also think `no-unused-enable` can also be deprecated since the following PR was merged:
https://github.com/eslint/eslint/pull/17611

**Comment by teppeis** [comment]
`reportUnusedDisableDirectives:error` released in https://eslint.org/blog/2023/12/eslint-v8.56.0-released/

**Comment by CruseCtrl** [comment]
> I think no-unused-disable should be deprecated

I've created #249 for this
