### ISSUE TITLE
Support `eslint-plugin-vue`'s disable comments

### ISSUE THREAD

**Issue by FloEdelmann** [eslint-community/eslint-plugin-eslint-comments#136]
In Vue Single File Components (`*.vue` files), "HTML comments" can be used to disable ESLint rules: https://eslint.vuejs.org/rules/comment-directive.html

```vue
<template>
  <!-- eslint-disable-next-line vue/max-attributes-per-line -->
  <div a="1" b="2" c="3" d="4" />
</template>
```

Unfortunately, those comments are not detected by `eslint-plugin-eslint-comments`.

**Comment by GrantGryczan** [comment]
I would also love to have this! Wonder how hard it'd be to PR.

**Comment by GrantGryczan** [comment]
Hey? I still care about this.

**Comment by FloEdelmann** [comment]
@MichaelDeBoey could you please reopen this issue and hide these comments as off-topic? The feature request is still valid.

**Comment by GrantGryczan** [comment]
I guess you could just recreate the issue?

**Comment by FloEdelmann** [comment]
Yep, did that now, see [#212](https://togithub.com/eslint-community/eslint-plugin-eslint-comments/issues/212).
