### ISSUE TITLE
ESLint 9 support

### ISSUE THREAD

**Issue by zloirock** [eslint-community/eslint-plugin-eslint-comments#199]
It's even not about flat configs, #182, it's about peer dependency:

![image](https://github.com/eslint-community/eslint-plugin-eslint-comments/assets/2213682/ef440d52-01e0-479f-a2c9-191046b4ff6b)

**Comment by voxpelli** [comment]
I think this was fixed by: https://github.com/eslint-community/eslint-plugin-eslint-comments/pull/206 But not yet released?
