### ISSUE TITLE
v4.0.0 dropped ESLint v8 support

### ISSUE THREAD

**Issue by aarongoldenthal** [eslint-community/eslint-plugin-eslint-comments#89]
In https://github.com/eslint-community/eslint-plugin-eslint-comments/pull/18/, support for ESLint v4 and v5 was dropped (the intent per the PR). The change leaves only `"peerDependencies": { "eslint": "^6.0.0 || ^7.0.0" }`, so also dropped ESLint v8 support.

**Comment by silverwind** [comment]
Yep, can no longer install it on v8:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: eslint@8.46.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"8.46.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^6.0.0 || ^7.0.0" from @eslint-community/eslint-plugin-eslint-comments@4.0.0
npm ERR! node_modules/@eslint-community/eslint-plugin-eslint-comments
npm ERR!   dev @eslint-community/eslint-plugin-eslint-comments@"4.0.0" from the root project
```

**Comment by ota-meshi** [comment]
@MichaelDeBoey This is the effect of change #18.
It was still supposed to be an alpha release and v4 was supposed to contain the #20 changes, but #20 was closed and v4 was released first.
We should merge #91 and open a pull request to support ESLint v8.

**Comment by MichaelDeBoey** [comment]
@aarongoldenthal @silverwind ESLint v8 was never _officially_ supported (we had no tests for it), but indeed something that we should support asap as technically there are no changes needed to support it
